name: build

on:
  push:
    paths:
      - 'README.md'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          # upx 3.95 for mips wait for 4.0 fix https://github.com/upx/upx/issues/342
          sudo apt-get update
          sudo apt-get install -y upx
          sudo rm -rf /usr/bin/go*
          sudo rm -rf /usr/local/go
          wget https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz -O go.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          tar xf upx-3.96-amd64_linux.tar.xz
          mv upx-3.96-amd64_linux/upx .
          rm -rf upx-3.96-amd64_linux*
          
          
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash          
          
      - name: build
        run: |
          mkdir tmp
          mkdir bin
          # Do not use "--depth=1" due to tags
          git clone https://github.com/XTLS/Xray-core.git
          cd Xray-core
          git checkout tags/v1.5.4
          cd ..
          wget https://raw.githubusercontent.com/chuntsky/xray-openwrt/master/build.sh
          chmod +x ./build.sh
          ./build.sh android arm64
          ./build.sh darwin amd64
          ./build.sh linux 386
          ./build.sh linux amd64
          ./build.sh linux armv5
          ./build.sh linux armv6
          ./build.sh linux armv7
          ./build.sh linux arm64
          ./build.sh linux mips
          ./build.sh linux mipsle
          ./build.sh linux mips64
          ./build.sh linux mips64le
          
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            bin/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_KEY }} 
          
#       - name: Upload artifact
#         uses: "marvinpinto/action-automatic-releases@latest"
#         with:
#           repo_token: "${{ secrets.UPLOAD_KEY }}"
#           prerelease: false
#           files: |
#             bin/*.tar.gz
